/*************************************************************************************@@
Class Name     :  ClientSideControllerTest
Purpose        :  Test class for ClientSideController
DATE           :  08/03/2021
Author         :  Anjali Sharma
*********************************************************************************************************/
@isTest
private class ClientSideControllerTest {
    @isTest static void getDataTest() {
        ClientSideController.getData();
    }
}